version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/authorization-service-narendra:4"
        LoadBalancerInfo:
          ContainerName: "authorization-service"
          ContainerPort: "8081"
        PlatformVersion: "LATEST"